/* =====================================================================
   Catálogos usados nas buscas (raças por espécie e fluidos).
   Para incluir itens, basta acrescentar às listas abaixo.
   ===================================================================== */
window.CATALOGOS = {
  RACAS: {
    'Cão': [
      'SRD (Sem raça definida)', 'Afghan Hound (Galgo Afegão)', 'Airedale Terrier', 'Akita Americano', 'Akita Inu',
      'American Bully', 'American Pit Bull Terrier', 'American Staffordshire Terrier', 'Basenji', 'Basset Hound',
      'Beagle', 'Bernese (Boiadeiro Bernês)', 'Bichon Frisé', 'Bloodhound', 'Boiadeiro Australiano (Blue Heeler)',
      'Border Collie', 'Border Terrier', 'Borzoi', 'Boston Terrier', 'Boxer', 'Braco Alemão (Pointer Alemão)',
      'Buldogue Americano', 'Buldogue Campeiro', 'Buldogue Francês', 'Buldogue Inglês', 'Bull Terrier', 'Bullmastiff',
      'Cairn Terrier', 'Cane Corso', 'Cavalier King Charles Spaniel', 'Chihuahua', 'Chow Chow', 'Cocker Spaniel Americano',
      'Cocker Spaniel Inglês', 'Collie', 'Coton de Tuléar', 'Dachshund (Teckel/Salsicha)', 'Dálmata', 'Doberman',
      'Dogo Argentino', 'Dogue Alemão (Dogue Dinamarquês)', 'Dogue de Bordeaux', 'Fila Brasileiro', 'Fox Paulistinha (Terrier Brasileiro)',
      'Fox Terrier', 'Galgo Inglês (Greyhound)', 'Galgo Italiano (Lebrel Italiano)', 'Golden Retriever', 'Husky Siberiano',
      'Jack Russell Terrier', 'Kuvasz', 'Labrador Retriever', 'Leonberger', 'Lhasa Apso', 'Lulu da Pomerânia (Spitz Alemão Anão)',
      'Malamute do Alasca', 'Maltês', 'Mastiff', 'Mastim Napolitano', 'Mastim Tibetano', 'Old English Sheepdog (Bobtail)',
      'Papillon', 'Pastor Alemão', 'Pastor Australiano', 'Pastor Belga Malinois', 'Pastor Branco Suíço', 'Pastor de Shetland',
      'Pastor Maremano Abruzês', 'Pequinês', 'Pinscher Miniatura', 'Pinscher Médio', 'Pointer Inglês', 'Poodle Toy',
      'Poodle Miniatura', 'Poodle Médio', 'Poodle Gigante (Standard)', 'Pug', 'Rhodesian Ridgeback', 'Rottweiler',
      'Samoieda', 'São Bernardo', 'Schnauzer Miniatura', 'Schnauzer Standard', 'Schnauzer Gigante', 'Scottish Terrier',
      'Setter Irlandês', 'Shar-Pei', 'Shiba Inu', 'Shih Tzu', 'Spitz Alemão', 'Springer Spaniel Inglês', 'Staffordshire Bull Terrier',
      'Terra Nova', 'Vizsla (Braco Húngaro)', 'Weimaraner', 'Welsh Corgi Pembroke', 'Welsh Corgi Cardigan', 'West Highland White Terrier',
      'Whippet', 'Yorkshire Terrier',
    ],
    'Gato': [
      'SRD (Sem raça definida)', 'Pelo Curto Brasileiro', 'Abissínio', 'American Shorthair', 'Angorá Turco', 'Azul Russo',
      'Balinês', 'Bengal', 'Birmanês (Sagrado da Birmânia)', 'Bombay', 'British Longhair', 'British Shorthair', 'Burmês',
      'Chartreux', 'Cornish Rex', 'Devon Rex', 'Egyptian Mau', 'Exótico (Exotic Shorthair)', 'Havana Brown', 'Himalaio',
      'Korat', 'LaPerm', 'Maine Coon', 'Manx', 'Munchkin', 'Norueguês da Floresta', 'Ocicat', 'Oriental de Pelo Curto',
      'Persa', 'Ragamuffin', 'Ragdoll', 'Savannah', 'Scottish Fold', 'Selkirk Rex', 'Siamês', 'Siberiano', 'Singapura',
      'Snowshoe', 'Somali', 'Sphynx', 'Tonquinês', 'Toyger', 'Van Turco',
    ],
    'Equino': [
      'SRD (Sem raça definida)', 'Andaluz (PRE)', 'Appaloosa', 'Árabe (Puro Sangue Árabe)', 'Bretão', 'Brasileiro de Hipismo',
      'Campeiro', 'Campolina', 'Crioulo', 'Frísio', 'Hanoveriano', 'Holsteiner', 'Lusitano', 'Mangalarga Marchador',
      'Mangalarga Paulista', 'Pampa', 'Paint Horse', 'Pantaneiro', 'Percheron', 'Piquira', 'Pônei Brasileiro', 'Pônei Shetland',
      'Puro Sangue Inglês (PSI)', 'Quarto de Milha', 'Trotador Americano (Standardbred)', 'Muar (mula/burro)', 'Jumento Pêga',
      'Jumento Nordestino',
    ],
  },

  PROCEDIMENTOS: [
    'Ovariohisterectomia eletiva',
    'Orquiectomia',
    'Profilaxia dentária / Tratamento periodontal',
    'Mastectomia',
    'Nodulectomia',
    'Enterotomia',
    'Cistotomia',
    'Osteossíntese',
    'Colocefalectomia',
    'TPLO',
    'Esplenectomia',
    'Cesariana',
    'Laparotomia exploratória',
    'Correção de hérnia',
    'Enucleação',
    'Tomografia computadorizada',
    'Ressonância magnética',
    'Laparotomia (cólica equina)',
    'Ovariosalpingohisterectomia (OSH) terapêutica / piometra',
    'Uretrostomia',
    'Gastrotomia',
    'Gastropexia',
    'Correção de dilatação-vólvulo gástrica',
    'Ressecção e anastomose intestinal',
    'Herniorrafia perineal',
    'Herniorrafia umbilical/inguinal',
    'Correção de ruptura de ligamento cruzado',
    'Correção de luxação de patela',
    'Amputação de membro',
    'Caudectomia (indicação clínica)',
    'Exérese de tumor cutâneo',
    'Biópsia',
    'Limpeza de ferida / desbridamento',
    'Extração dentária',
    'Endoscopia',
    'Colonoscopia',
    'Rinoscopia',
    'Broncoscopia',
    'Ecocardiograma sob sedação',
    'Mielografia',
    'Facoemulsificação (catarata)',
    'Correção de entrópio',
    'Flap de terceira pálpebra',
    'Ablação total do conduto auditivo',
    'Tireoidectomia',
    'Adrenalectomia',
    'Nefrectomia',
    'Colecistectomia',
    'Correção de persistência do ducto arterioso (PDA)',
    'Correção de shunt portossistêmico',
    'Rinoplastia / palatoplastia (braquicefálicos)',
    'Sedação para exame de imagem',
    'Castração equina',
    'Artroscopia equina',
    'Neurectomia equina',
    'Correção de fratura (osteossíntese) equina',
  ],

  // Fluidos: nome completo + sigla (busca por qualquer um dos dois e pelos apelidos).
  FLUIDOS: [
    { nome: 'Ringer com Lactato', sigla: 'RL', alias: ['Ringer Lactato', 'Lactato de Ringer', 'Hartmann'] },
    { nome: 'Ringer Simples', sigla: 'RS', alias: ['Solução de Ringer'] },
    { nome: 'Cloreto de Sódio 0,9% (Solução Fisiológica)', sigla: 'NaCl 0,9%', alias: ['SF 0,9%', 'Soro Fisiológico', 'Salina'] },
    { nome: 'Cloreto de Sódio 0,45%', sigla: 'NaCl 0,45%', alias: ['Salina 0,45%', 'Meio Fisiológico'] },
    { nome: 'Cloreto de Sódio 3% (Hipertônica)', sigla: 'NaCl 3%', alias: ['Salina Hipertônica 3%'] },
    { nome: 'Cloreto de Sódio 7,5% (Hipertônica)', sigla: 'NaCl 7,5%', alias: ['SSH 7,5%', 'Salina Hipertônica 7,5%'] },
    { nome: 'Glicose 5% (Soro Glicosado)', sigla: 'SG 5%', alias: ['Dextrose 5%', 'D5W'] },
    { nome: 'Glicose 10%', sigla: 'SG 10%', alias: ['Dextrose 10%'] },
    { nome: 'Glicose 50%', sigla: 'G 50%', alias: ['Dextrose 50%'] },
    { nome: 'Solução Glicofisiológica (NaCl 0,9% + Glicose 5%)', sigla: 'SGF', alias: ['Glicofisiológico'] },
    { nome: 'Ringer com Lactato + Glicose 2,5%', sigla: 'RL + G 2,5%', alias: [] },
    { nome: 'Plasma-Lyte A / 148', sigla: 'PL', alias: ['Plasmalyte', 'Solução balanceada'] },
    { nome: 'Normosol-R', sigla: 'NR', alias: ['Normosol'] },
    { nome: 'Bicarbonato de Sódio 8,4%', sigla: 'NaHCO₃ 8,4%', alias: ['Bicarbonato'] },
    { nome: 'Cloreto de Potássio 19,1% (aditivo)', sigla: 'KCl', alias: ['Potássio'] },
    { nome: 'Gluconato de Cálcio 10%', sigla: 'Gluc. Ca 10%', alias: ['Cálcio'] },
    { nome: 'Manitol 20%', sigla: 'Manitol', alias: [] },
    { nome: 'Hidroxietilamido 6% (Voluven)', sigla: 'HES 6%', alias: ['Amido', 'Coloide sintético', 'Voluven'] },
    { nome: 'Gelatina Succinilada (Gelafundin)', sigla: 'Gelatina', alias: ['Gelafundin', 'Coloide'] },
    { nome: 'Dextrana 40', sigla: 'Dextran 40', alias: ['Coloide'] },
    { nome: 'Albumina Humana 20%', sigla: 'Alb 20%', alias: ['Albumina'] },
    { nome: 'Plasma Fresco Congelado', sigla: 'PFC', alias: ['Plasma'] },
    { nome: 'Sangue Total', sigla: 'ST', alias: ['Transfusão'] },
    { nome: 'Concentrado de Hemácias', sigla: 'CH', alias: ['Papa de hemácias', 'Transfusão'] },
  ],
};
// Texto gravado na ficha e no PDF: "Nome completo (SIGLA)".
window.CATALOGOS.fluidoTexto = f => `${f.nome} (${f.sigla})`;
